version: '2.4'
volumes:
 config_cassandra:
 config_zookeeper:
services:
  node-init:
    image: "{{ container_registry }}/opensdn-node-init:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - CONTRAIL_STATUS_IMAGE="{{ container_registry }}/opensdn-status:{{ contrail_version_tag }}"
    privileged: true
    pid: host
    network_mode: "host"
    volumes:
      - /usr/bin:/host/usr/bin
      - /etc/contrail/ssl/{{ module }}:/etc/contrail/ssl
      - /etc/sysctl.d:/etc/sysctl.d
      - /etc/hosts:/etc/hosts
      - /var/log/contrail:/var/log/contrail
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/crashes:/var/crashes
{{ logging | indent(4,True) }}
  nodemgr:
    image: "{{ container_registry }}/opensdn-nodemgr:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - NODE_TYPE=config-database
      - CASSANDRA_CQL_PORT=9041
      - CASSANDRA_JMX_LOCAL_PORT=7201
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - node-init
    depends_on:
      - node-init
    restart: always
{{ logging | indent(4,True) }}
{% if contrail_version >= 2002 %}
  provisioner:
    image: "{{ container_registry }}/opensdn-provisioner:{{ contrail_version_tag }}"
    env_file:
      - /etc/contrail/common_config.env
    environment:
      - NODE_TYPE=config-database
    network_mode: "host"
    volumes_from:
      - node-init
    depends_on:
      - node-init
    restart: on-failure
{{ logging | indent(4,True) }}
{% endif %}
  cassandra:
    image: "{{ container_registry }}/opensdn-external-cassandra:{{ contrail_version_tag }}"
{% if container_runtime == 'docker' %}
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
{% else %}
    privileged: true
{% endif %}
    env_file: /etc/contrail/common_config.env
    environment:
      - CASSANDRA_SEEDS={{ controller_servers|sort|join(',') }}
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=contrail_database
      - CASSANDRA_PORT=9161
      - CASSANDRA_CQL_PORT=9041
      - CASSANDRA_SSL_STORAGE_PORT=7013
      - CASSANDRA_STORAGE_PORT=7012
      - CASSANDRA_JMX_LOCAL_PORT=7201
      - NODE_TYPE=config-database
    volumes:
      - config_cassandra:/var/lib/cassandra/data
    {% if contrail_version >= 2008 %}
      - /var/log/contrail/config-database:/var/log/cassandra
    {% endif %}
    volumes_from:
      - node-init
    depends_on:
      - node-init
    network_mode: "host"
    restart: always
{{ logging | indent(4,True) }}
  zookeeper:
    image: "{{ container_registry }}/opensdn-external-zookeeper:{{ contrail_version_tag }}"
    env_file: /etc/contrail/common_config.env
    environment:
      - ZOOKEEPER_NODES={{ controller_servers|sort|join(',') }}
      - ZOOKEEPER_PORTS=2888:3888
      - ZOOKEEPER_PORT=2181
      - NODE_TYPE=config-database
    volumes:
      - config_zookeeper:/data
      - config_zookeeper:/datalog
    {% if contrail_version >= 2008 %}
      - /var/log/contrail/zookeeper:/var/log/zookeeper
    {% endif %}
    volumes_from:
      - node-init
    depends_on:
      - node-init
    network_mode: "host"
    restart: always
{{ logging | indent(4,True) }}
  rabbitmq:
    image: "{{ container_registry }}/opensdn-external-rabbitmq:{{ contrail_version_tag }}"
{% if container_runtime == 'containerd' %}
    entrypoint: ["/bin/bash", "-c", "ulimit -n 4096 && /opensdn-entrypoint.sh rabbitmq-server"]
    privileged: true
{% endif %}
    env_file: /etc/contrail/common_config.env
    environment:
      - RABBITMQ_NODES={{ controller_servers|sort|join(',') }}
      - RABBITMQ_ERLANG_COOKIE=abcdefg
      - NODE_TYPE=config-database
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbitmq.log
      - RAMMITMQ_SASL_LOGS=/var/log/rabbitmq/rabbitmq_sasl.log
    {% if contrail_version >= 2008 %}
    volumes:
      - /var/log/contrail/rabbitmq:/var/log/rabbitmq
    {% endif %}
    volumes_from:
      - node-init
    depends_on:
      - node-init
    network_mode: "host"
    restart: always
{{ logging | indent(4,True) }}
